version: '3'

services:

  db:
    container_name: ${APP_ID}_db
    image: 'mysql:5.7'
    restart: unless-stopped
    env_file: .env
    tty: true
    environment:
      - MYSQL_DATABASE=app
    volumes:
      - 'ecom-dbdata:/var/lib/mysql'
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - ecom_app_network

  php:
    build:
      context: ./php
    container_name: ${APP_ID}_app
    restart: unless-stopped
    tty: true
    volumes:
      - './app:/app'
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    working_dir: /app
    networks:
      - ecom_app_network

  # web:
  #   build: ./nginx
  #   container_name: ${APP_ID}_web
  #   restart: unless-stopped
  #   tty: true
  #   volumes:
  #     - './app:/app'
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #   depends_on:
  #     - php
  #   ports:
  #     - '${PORT:-80}:80'
  #   networks:
  #     - ecom_app_network

  web:
    build: ./apache2
    container_name: ${APP_ID}_web
    restart: unless-stopped
    tty: true
    volumes:
      - './app:/var/www/html/'
    depends_on:
      - db
      - php
    ports:
      - '${PORT:-80}:80'
    networks:
      - ecom_app_network


networks:
  ecom_app_network:
    driver: bridge

volumes:
  ecom-dbdata:
    driver: local
